name: Bug Report
description: Report an issue
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure issue is not duplicated and has filled corresponding labels.
  - type: textarea
    attributes:
      label: 'Description'
      description: A concise description of issue you're facing.
    validations:
      required: true