name: Enhancement Request
labels:
  - "type: enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search the repository to see if if this enhancement was already requested. If it does, add your perspective to its comments instead of creating a new one. Also make sure, that you've added any relevant labels to this issue. 
      options:
        - label: I have searched the existing issues and added correct labels.
          required: true
  - type: textarea
    id: related-feature
    attributes:
      label: Please describe the feature you have in mind and explain what the current shortcomings are?
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal
    attributes:
      label: Suggested implementation?
      description: If you have an idea about how to implement this enhancement from a technical standpoint, feel free to share any details here.
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered:"
      description: A clear and concise description of any alternative solutions to the problem this would solve you've considered. Are there other approaches to get the same result. Any workarounds at the moment?
